### ISSUE TITLE
errors on ubuntu 18.04

### ISSUE THREAD

**Issue by lgkgithub** [ucsb-seclab/difuze#6]
Hello,I'm trying build on 18.04,and I meet the following issues:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/difuze/helper_scripts/difuze_deps/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:281:22: error: aggregate ‘sigaltstack handler_stack’ has incomplete type and cannot be defined
   struct sigaltstack handler_stack;
                      ^~~~~~~~~~~~~
projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/build.make:206: recipe for target 'projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/sanitizer_stoptheworld_linux_libcdep.cc.o' failed
make[2]: *** [projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/sanitizer_stoptheworld_linux_libcdep.cc.o] Error 1
CMakeFiles/Makefile2:13255: recipe for target 'projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/all' failed
make[1]: *** [projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
[+]  Build Complete.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Any help would be appreciated.

**Comment by ytrewqytrewqytrewqytrewq1** [comment]
try to build it on a previous version of ubuntu 14 and 16 worked mostly fine, you will encounter countless more problems with this project

**Comment by Machiry** [comment]
We haven't tested it on ubuntu 18.04 :( 
I would soon (by end of this week) build a docker setup to run difuze.

**Comment by peperunas** [comment]
This should be related to LLVM being incompatible to the latest glibc: https://reviews.llvm.org/D35246

**Comment by lgkgithub** [comment]
thanks!I build on ubuntu 16 and everything seems good!
